souffle: souffle::RamLogTimer Class Reference
souffle::RamLogTimer Class Reference
Execution time logger for a statement.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamLogTimer * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const std::string & getMessage () const
get logging message
const RamRelation * getRelation () const
get logged relation
const RamStatement & getStatement () const
get logging statement
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamLogTimer (std::unique_ptr< RamStatement > stmt, std::string msg, std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::string message
logging message
std::unique_ptr< RamRelationReference > relationRef
Relation.
std::unique_ptr< RamStatement > statement
logging statement
Detailed Description
Execution time logger for a statement.
Logs the execution time of a statement. Before and after the execution of the logging statement the wall-clock time is taken to compute the time duration for the statement. Duration and logging message is printed after the execution of the statement.
Definition at line 671 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamLogTimer::RamLogTimer (std::unique_ptr< RamStatement > stmt, std::string msg, std::unique_ptr< RamRelationReference > relRef) inline
Definition at line 673 of file RamStatement.h.
             : RamStatement(), statement(std::move(stmt)), message(std::move(msg)),
               relationRef(std::move(relRef)) {
         assert(statement);
     }
Member Function Documentation
void souffle::RamLogTimer::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 716 of file RamStatement.h.
{
         statement = map(std::move(statement));
     }
RamLogTimer* souffle::RamLogTimer::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 710 of file RamStatement.h.
{
         auto* res = new RamLogTimer(std::unique_ptr<RamStatement>(statement->clone()), message,
                 std::unique_ptr<RamRelationReference>(relationRef->clone()));
         return res;
     }
bool souffle::RamLogTimer::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 730 of file RamStatement.h.
References statement.
{
         assert(nullptr != dynamic_cast<const RamLogTimer*>(&node));
         const auto& other = static_cast<const RamLogTimer&>(node);
         return *statement == *other.statement && message == other.message;
     }
std::vector<const RamNode*> souffle::RamLogTimer::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 706 of file RamStatement.h.
{
         return {statement.get()};
     }
const std::string& souffle::RamLogTimer::getMessage () const inline
get logging message
Definition at line 681 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalStmt(), and souffle::LVMGenerator::visitLogTimer().
{
         return message;
     }
const RamRelation* souffle::RamLogTimer::getRelation () const inline
get logged relation
Definition at line 692 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalStmt(), and souffle::LVMGenerator::visitLogTimer().
{
         if (relationRef != nullptr) {
             return relationRef->get();
         } else {
             return nullptr;
         }
     }
const RamStatement& souffle::RamLogTimer::getStatement () const inline
get logging statement
Definition at line 686 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamDebugInfo::equal(), souffle::RAMI::evalStmt(), and souffle::LVMGenerator::visitLogTimer().
{
         assert(statement);
         return *statement;
     }
void souffle::RamLogTimer::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 700 of file RamStatement.h.
References souffle::stringify(), and souffle::times().
{
         os << times(" ", tabpos) << "START_TIMER \"" << stringify(message) << "\"" << std::endl;
         statement->print(os, tabpos + 1);
         os << times(" ", tabpos) << "END_TIMER" << std::endl;
     }
Field Documentation
std::string souffle::RamLogTimer::message protected
logging message
Definition at line 725 of file RamStatement.h.
std::unique_ptr<RamRelationReference> souffle::RamLogTimer::relationRef protected
Relation.
Definition at line 728 of file RamStatement.h.
std::unique_ptr<RamStatement> souffle::RamLogTimer::statement protected
logging statement
Definition at line 722 of file RamStatement.h.
Referenced by equal().
The documentation for this class was generated from the following file:
RamStatement.h