souffle: souffle::InterpreterRelation Class Reference
souffle::InterpreterRelation Class Reference
Interpreter Relation.
#include <InterpreterRelation.h>
Data Structures
class iterator
Iterator for relation.
Public Member Functions
iterator begin () const
get iterator begin of relation
bool empty () const
Check whether relation is empty.
iterator end () const
get iterator begin of relation
bool exists (const RamDomain *tuple) const
check whether a tuple exists in the relation
virtual std::vector< RamDomain * > extend (const RamDomain *tuple)
Extend tuple.
virtual void extend (const InterpreterRelation &rel)
Extend relation.
size_t getArity () const
Get arity of relation.
std::vector< std::string > & getAttributeTypeQualifiers ()
Get AttributeType for the relation.
InterpreterIndex * getIndex (const SearchSignature &col) const
get index for a given search signature.
InterpreterIndex * getIndexByPos (int idx) const
get index for a given order.
size_t getLevel ()
SearchSignature getTotalIndexKey () const
Obtains a full index-key for this relation.
virtual void insert (const RamDomain *tuple)
Insert tuple.
void insert (const InterpreterRelation &other)
Merge another relation into this relation.
InterpreterRelation (size_t relArity, const MinIndexSelection *orderSet)
InterpreterRelation (const InterpreterRelation &other)=delete
void purge ()
Purge table.
void setAttributes (const std::vector< std::string > attributeTypes)
Set AttributeType for the relation.
void setLevel (size_t level)
size_t size () const
Gets the number of contained tuples.
virtual ~InterpreterRelation ()=default
Private Types
using LexOrder = std::vector< int >
Private Attributes
const size_t arity
Arity of relation.
std::vector< std::string > attributeTypeQualifiers
Type of attributes.
std::deque< std::unique_ptr< RamDomain[]> > blockList
std::vector< InterpreterIndex > indices
List of indices.
size_t level = 0
Stratum level information.
Lock lock
Lock for parallel execution.
size_t num_tuples = 0
Number of tuples in relation.
const MinIndexSelection * orderSet
IndexSet.
Static Private Attributes
static const int BLOCK_SIZE = 1024
Size of blocks containing tuples.
Detailed Description
Interpreter Relation.
Definition at line 35 of file InterpreterRelation.h.
Member Typedef Documentation
using souffle::InterpreterRelation::LexOrder = std::vector<int> private
Definition at line 36 of file InterpreterRelation.h.
Constructor & Destructor Documentation
souffle::InterpreterRelation::InterpreterRelation (size_t relArity, const MinIndexSelection * orderSet) inline
Definition at line 39 of file InterpreterRelation.h.
References souffle::MinIndexSelection::getAllOrders(), indices, and ~InterpreterRelation().
             : arity(relArity), orderSet(orderSet) {
         // Create all necessary indices based on orderSet
         for (auto& order : orderSet->getAllOrders()) {
             indices.push_back(InterpreterIndex(order));
         }
     }
souffle::InterpreterRelation::InterpreterRelation (const InterpreterRelation & other) delete
virtual souffle::InterpreterRelation::~InterpreterRelation () virtual default
Referenced by InterpreterRelation().
Member Function Documentation
iterator souffle::InterpreterRelation::begin () const inline
get iterator begin of relation
Definition at line 214 of file InterpreterRelation.h.
References empty(), end(), and souffle::InterpreterRelation::iterator::iterator().
Referenced by souffle::InterpreterRelInterface::begin().
{
         // check for emptiness
         if (empty()) {
             return end();
         }
         return iterator(this);
     }
bool souffle::InterpreterRelation::empty () const inline
Check whether relation is empty.
Definition at line 67 of file InterpreterRelation.h.
References num_tuples.
Referenced by begin().
{
         return num_tuples == 0;
     }
iterator souffle::InterpreterRelation::end () const inline
get iterator begin of relation
Definition at line 224 of file InterpreterRelation.h.
References souffle::InterpreterRelation::iterator::iterator().
Referenced by begin(), and souffle::InterpreterRelInterface::end().
{
         return iterator();
     }
bool souffle::InterpreterRelation::exists (const RamDomain * tuple) const inline
check whether a tuple exists in the relation
Definition at line 150 of file InterpreterRelation.h.
References souffle::InterpreterIndex::exists(), getIndex(), and getTotalIndexKey().
Referenced by souffle::InterpreterRelInterface::contains(), souffle::RAMI::evalCond(), souffle::LVM::execute(), and insert().
{
         InterpreterIndex* index = getIndex(getTotalIndexKey());
         return index->exists(tuple);
     }
virtual std::vector<RamDomain*> souffle::InterpreterRelation::extend (const RamDomain * tuple) inline virtual
Extend tuple.
Reimplemented in souffle::InterpreterEqRelation.
Definition at line 229 of file InterpreterRelation.h.
Referenced by souffle::RAMI::evalStmt(), souffle::LVM::execute(), souffle::InterpreterEqRelation::extend(), and souffle::InterpreterEqRelation::insert().
{
         std::vector<RamDomain*> newTuples;
         // A standard relation does not generate extra new knowledge on insertion.
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
         return newTuples;
     }
virtual void souffle::InterpreterRelation::extend (const InterpreterRelation & rel) inline virtual
Extend relation.
Reimplemented in souffle::InterpreterEqRelation.
Definition at line 239 of file InterpreterRelation.h.
 {}
size_t souffle::InterpreterRelation::getArity () const inline
Get arity of relation.
Definition at line 62 of file InterpreterRelation.h.
References arity.
Referenced by souffle::RAMI::evalCond(), souffle::RAMI::evalOp(), souffle::LVM::execute(), souffle::InterpreterRelInterface::getArity(), getTotalIndexKey(), and insert().
{
         return arity;
     }
std::vector<std::string>& souffle::InterpreterRelation::getAttributeTypeQualifiers () inline
Get AttributeType for the relation.
Definition at line 57 of file InterpreterRelation.h.
References attributeTypeQualifiers.
Referenced by souffle::LVM::execute().
{
         return attributeTypeQualifiers;
     }
InterpreterIndex* souffle::InterpreterRelation::getIndex (const SearchSignature & col) const inline
get index for a given search signature.
Order are encoded as bits for each column
Definition at line 131 of file InterpreterRelation.h.
References arity, getIndexByPos(), souffle::MinIndexSelection::getLexOrderNum(), getTotalIndexKey(), and orderSet.
Referenced by souffle::RAMI::evalCond(), souffle::RAMI::evalOp(), and exists().
{
         // Special case in provenance program, a 0 searchSignature is considered as a full search
         if (col == 0 && arity != 0) {
             return getIndex(getTotalIndexKey());
         }
         return getIndexByPos(orderSet->getLexOrderNum(col));
     }
InterpreterIndex* souffle::InterpreterRelation::getIndexByPos (int idx) const inline
get index for a given order.
Order are encoded as bits for each column
Definition at line 140 of file InterpreterRelation.h.
References indices.
Referenced by souffle::LVM::execute(), and getIndex().
{
         return &indices[idx];
     }
size_t souffle::InterpreterRelation::getLevel () inline
Definition at line 159 of file InterpreterRelation.h.
References level.
                       {
         return this->level;
     }
SearchSignature souffle::InterpreterRelation::getTotalIndexKey () const inline
Obtains a full index-key for this relation.
Definition at line 145 of file InterpreterRelation.h.
References getArity().
Referenced by exists(), and getIndex().
{
         return (1 << (getArity())) - 1;
     }
virtual void souffle::InterpreterRelation::insert (const RamDomain * tuple) inline virtual
Insert tuple.
Reimplemented in souffle::InterpreterEqRelation.
Definition at line 77 of file InterpreterRelation.h.
References arity, BLOCK_SIZE, blockList, exists(), i, indices, and num_tuples.
Referenced by souffle::RAMI::evalOp(), souffle::RAMI::evalStmt(), souffle::LVM::execute(), souffle::InterpreterEqRelation::extend(), souffle::InterpreterRelInterface::insert(), insert(), and souffle::InterpreterEqRelation::insert().
{
         assert(tuple);
         // make existence check
         if (exists(tuple)) {
             return;
         }
         // check for null-arity
         if (arity == 0) {
             indices[0].insert(tuple);
             num_tuples = 1;
             return;
         }
         int blockIndex = num_tuples / (BLOCK_SIZE / arity);
         int tupleIndex = (num_tuples % (BLOCK_SIZE / arity)) * arity;
         if (tupleIndex == 0) {
             blockList.push_back(std::make_unique<RamDomain[]>(BLOCK_SIZE));
         }
         RamDomain* newTuple = &blockList[blockIndex][tupleIndex];
         for (size_t i = 0; i < arity; ++i) {
             newTuple[i] = tuple[i];
         }
         // update all indexes with new tuple
         for (auto& cur : indices) {
             cur.insert(newTuple);
         }
         // increment relation size
         num_tuples++;
     }
void souffle::InterpreterRelation::insert (const InterpreterRelation & other) inline
Merge another relation into this relation.
Definition at line 114 of file InterpreterRelation.h.
References getArity(), and insert().
{
         assert(getArity() == other.getArity());
         for (const auto& cur : other) {
             insert(cur);
         }
     }
void souffle::InterpreterRelation::purge () inline
Purge table.
Definition at line 122 of file InterpreterRelation.h.
References blockList, indices, and num_tuples.
Referenced by souffle::RAMI::evalStmt(), and souffle::InterpreterRelInterface::purge().
                  {
         blockList.clear();
         for (auto& cur : indices) {
             cur.purge();
         }
         num_tuples = 0;
     }
void souffle::InterpreterRelation::setAttributes (const std::vector< std::string > attributeTypes) inline
Set AttributeType for the relation.
Definition at line 52 of file InterpreterRelation.h.
References attributeTypeQualifiers.
Referenced by souffle::LVM::execute().
{
         attributeTypeQualifiers = attributeTypes;
     }
void souffle::InterpreterRelation::setLevel (size_t level) inline
Definition at line 155 of file InterpreterRelation.h.
References level.
Referenced by souffle::LVM::execute().
{
         this->level = level;
     }
size_t souffle::InterpreterRelation::size () const inline
Gets the number of contained tuples.
Definition at line 72 of file InterpreterRelation.h.
References num_tuples.
Referenced by souffle::RAMI::evalStmt(), souffle::LVM::execute(), and souffle::InterpreterRelInterface::size().
{
         return num_tuples;
     }
Field Documentation
const size_t souffle::InterpreterRelation::arity private
Arity of relation.
Definition at line 243 of file InterpreterRelation.h.
Referenced by getArity(), getIndex(), insert(), and souffle::InterpreterRelation::iterator::operator++().
std::vector<std::string> souffle::InterpreterRelation::attributeTypeQualifiers private
Type of attributes.
Definition at line 263 of file InterpreterRelation.h.
Referenced by getAttributeTypeQualifiers(), and setAttributes().
const int souffle::InterpreterRelation::BLOCK_SIZE = 1024 static private
Size of blocks containing tuples.
Definition at line 246 of file InterpreterRelation.h.
Referenced by insert(), and souffle::InterpreterRelation::iterator::operator++().
std::deque<std::unique_ptr<RamDomain[]> > souffle::InterpreterRelation::blockList private
Definition at line 251 of file InterpreterRelation.h.
Referenced by insert(), souffle::InterpreterRelation::iterator::operator++(), and purge().
std::vector<InterpreterIndex> souffle::InterpreterRelation::indices mutable private
List of indices.
Definition at line 254 of file InterpreterRelation.h.
Referenced by getIndexByPos(), insert(), InterpreterRelation(), and purge().
size_t souffle::InterpreterRelation::level = 0 private
Stratum level information.
Definition at line 266 of file InterpreterRelation.h.
Referenced by getLevel(), and setLevel().
Lock souffle::InterpreterRelation::lock mutable private
Lock for parallel execution.
Definition at line 260 of file InterpreterRelation.h.
size_t souffle::InterpreterRelation::num_tuples = 0 private
Number of tuples in relation.
Definition at line 249 of file InterpreterRelation.h.
Referenced by empty(), insert(), souffle::InterpreterRelation::iterator::operator++(), purge(), and size().
const MinIndexSelection* souffle::InterpreterRelation::orderSet private
IndexSet.
Definition at line 257 of file InterpreterRelation.h.
Referenced by getIndex().
The documentation for this class was generated from the following file:
InterpreterRelation.h