souffle: souffle::InterpreterIndex Class Reference
souffle::InterpreterIndex Class Reference
#include <InterpreterIndex.h>
Data Structures
struct comparator
Public Types
using index_set = btree_multiset< const RamDomain *, comparator, std::allocator< const RamDomain * >, 512 >
using iterator = index_set::iterator
Public Member Functions
std::pair< iterator, iterator > equalRange (const RamDomain *value)
return start and end iterator of an equal range
bool exists (const RamDomain *value)
check whether tuple exists in index
std::pair< iterator, iterator > getIteratorPair () const
return start and end iterator of the index set
void insert (const RamDomain *tuple)
add tuple to the index
template<class Iter >
void insert (const Iter &a, const Iter &b)
add tuples to the index via an iterator
InterpreterIndex (LexOrder order)
InterpreterIndex (const InterpreterIndex &&index)
std::pair< iterator, iterator > lowerUpperBound (const RamDomain *low, const RamDomain *high)
return start and end iterator of a range
const LexOrder & order () const
void print (std::ostream &out) const
enables the index to be printed
void purge ()
purge all hashes of index
Private Types
using LexOrder = std::vector< int >
Private Attributes
index_set::btree_operation_hints< 1 > operation_hints
Operation hints.
index_set set
set storing tuple pointers of table
const LexOrder theOrder
retain the index order used to construct an object of this class
Detailed Description
Definition at line 30 of file InterpreterIndex.h.
Member Typedef Documentation
using souffle::InterpreterIndex::index_set = btree_multiset<const RamDomain*, comparator, std::allocator<const RamDomain*>, 512>
Definition at line 71 of file InterpreterIndex.h.
using souffle::InterpreterIndex::iterator = index_set::iterator
Definition at line 73 of file InterpreterIndex.h.
using souffle::InterpreterIndex::LexOrder = std::vector<int> private
Definition at line 31 of file InterpreterIndex.h.
Constructor & Destructor Documentation
souffle::InterpreterIndex::InterpreterIndex (LexOrder order) inline
Definition at line 75 of file InterpreterIndex.h.
             : theOrder(std::move(order)), set(comparator(theOrder), comparator(theOrder)) {}
souffle::InterpreterIndex::InterpreterIndex (const InterpreterIndex && index) inline
Definition at line 78 of file InterpreterIndex.h.
             : theOrder(std::move(index.theOrder)), set(std::move(index.set)) {}
Member Function Documentation
std::pair<iterator, iterator> souffle::InterpreterIndex::equalRange (const RamDomain * value) inline
return start and end iterator of an equal range
Definition at line 123 of file InterpreterIndex.h.
References lowerUpperBound().
{
         return lowerUpperBound(value, value);
     }
bool souffle::InterpreterIndex::exists (const RamDomain * value) inline
check whether tuple exists in index
Definition at line 105 of file InterpreterIndex.h.
References operation_hints.
Referenced by souffle::InterpreterRelation::exists().
{
         return set.find(value, operation_hints) != set.end();
     }
std::pair<iterator, iterator> souffle::InterpreterIndex::getIteratorPair () const inline
return start and end iterator of the index set
Definition at line 134 of file InterpreterIndex.h.
{
         return std::pair<iterator, iterator>(set.begin(), set.end());
     }
void souffle::InterpreterIndex::insert (const RamDomain * tuple) inline
add tuple to the index
precondition: tuple does not exist in the index
Definition at line 90 of file InterpreterIndex.h.
References operation_hints.
{
         set.insert(tuple, operation_hints);
     }
template<class Iter > void souffle::InterpreterIndex::insert (const Iter & a, const Iter & b) inline
add tuples to the index via an iterator
precondition: the tuples do not exist in the index
Definition at line 100 of file InterpreterIndex.h.
{
         set.insert(a, b);
     };
std::pair<iterator, iterator> souffle::InterpreterIndex::lowerUpperBound (const RamDomain * low, const RamDomain * high) inline
return start and end iterator of a range
Definition at line 128 of file InterpreterIndex.h.
References operation_hints.
Referenced by equalRange().
{
         return std::pair<iterator, iterator>(
                 set.lower_bound(low, operation_hints), set.upper_bound(high, operation_hints));
     }
const LexOrder& souffle::InterpreterIndex::order () const inline
Definition at line 81 of file InterpreterIndex.h.
References theOrder.
{
         return theOrder;
     }
void souffle::InterpreterIndex::print (std::ostream & out) const inline
enables the index to be printed
Definition at line 116 of file InterpreterIndex.h.
{
         set.printStats(out);
         out << "\n";
         set.printTree(out);
     }
void souffle::InterpreterIndex::purge () inline
purge all hashes of index
Definition at line 110 of file InterpreterIndex.h.
References operation_hints.
                  {
         set.clear();
         operation_hints.clear();
     }
Field Documentation
index_set::btree_operation_hints<1> souffle::InterpreterIndex::operation_hints private
Operation hints.
Definition at line 146 of file InterpreterIndex.h.
Referenced by exists(), insert(), lowerUpperBound(), and purge().
index_set souffle::InterpreterIndex::set private
set storing tuple pointers of table
Definition at line 143 of file InterpreterIndex.h.
const LexOrder souffle::InterpreterIndex::theOrder private
retain the index order used to construct an object of this class
Definition at line 140 of file InterpreterIndex.h.
Referenced by order().
The documentation for this class was generated from the following file:
InterpreterIndex.h