souffle: souffle::RamLevelAnalysis Class Reference
souffle::RamLevelAnalysis Class Reference
A Ram Analysis for determining the level of a expression/condition.
#include <RamLevelAnalysis.h>
Public Member Functions
int getLevel (const RamNode *value) const
Get level of a RAM expression/condition.
void run (const RamTranslationUnit &translationUnit) override
run analysis for a RAM translation unit
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "level-analysis"
Detailed Description
A Ram Analysis for determining the level of a expression/condition.
The expression is determined by the ElementAccess of an expression/condition with the highest tuple-id number. Note in the implementation we assume that the tuple-id of RamSearch operations are ordered, i.e., the most-outer loop has the smallest tuple-id and the most inner-loop has the largest tuple-id number.
If an expression/condition does not contain an ElementAccess accessing an element of a tuple, the analysis yields -1 for denoting that the expression/condition can be executed outside of the loop-nest, i.e., the expression/condition is independent of data stemming from relations.
Definition at line 41 of file RamLevelAnalysis.h.
Member Function Documentation
int souffle::RamLevelAnalysis::getLevel (const RamNode * value) const
Get level of a RAM expression/condition.
Definition at line 23 of file RamLevelAnalysis.cpp.
References b, souffle::RamIntrinsicOperator::getArguments(), souffle::RamUserDefinedOperator::getArguments(), souffle::RamPackRecord::getArguments(), souffle::RamChoice::getCondition(), souffle::RamIndexChoice::getCondition(), souffle::RamAggregate::getCondition(), souffle::RamIndexAggregate::getCondition(), souffle::RamFilter::getCondition(), souffle::RamBreak::getCondition(), souffle::RamAggregate::getExpression(), souffle::RamIndexAggregate::getExpression(), souffle::RamUnpackRecord::getExpression(), souffle::RamConjunction::getLHS(), souffle::RamConstraint::getLHS(), souffle::RamNegation::getOperand(), souffle::RamIndexRelationSearch::getRangePattern(), souffle::RamConjunction::getRHS(), souffle::RamConstraint::getRHS(), souffle::RamElementAccess::getTupleId(), souffle::RamAbstractExistenceCheck::getValues(), souffle::RamProject::getValues(), souffle::RamReturnValue::getValues(), souffle::pack(), and souffle::unpack().
Referenced by run().
{
     // visitor
     class ValueLevelVisitor : public RamVisitor<int> {
     public:
         // number
         int visitNumber(const RamNumber& num) override {
             return -1;
         }
         // true
         int visitTrue(const RamTrue& t) override {
             return -1;
         }
         // false
         int visitFalse(const RamFalse& f) override {
             return -1;
         }
         // tuple element access
         int visitElementAccess(const RamElementAccess& elem) override {
             return elem.getTupleId();
         }
         // scan
         int visitScan(const RamScan& scan) override {
             return -1;
         }
         // index scan
         int visitIndexScan(const RamIndexScan& indexScan) override {
             int level = -1;
             for (auto& index : indexScan.getRangePattern()) {
                 if (index != nullptr) {
                     level = std::max(level, visit(index));
                 }
             }
             return level;
         }
         // choice
         int visitChoice(const RamChoice& choice) override {
             return std::max(-1, visit(choice.getCondition()));
         }
         // index choice
         int visitIndexChoice(const RamIndexChoice& indexChoice) override {
             int level = -1;
             for (auto& index : indexChoice.getRangePattern()) {
                 if (index != nullptr) {
                     level = std::max(level, visit(index));
                 }
             }
             return std::max(level, visit(indexChoice.getCondition()));
         }
         // aggregate
         int visitAggregate(const RamAggregate& aggregate) override {
             return std::max(visit(aggregate.getExpression()), visit(aggregate.getCondition()));
         }
         // index aggregate
         int visitIndexAggregate(const RamIndexAggregate& indexAggregate) override {
             int level = -1;
             for (auto& index : indexAggregate.getRangePattern()) {
                 if (index != nullptr) {
                     level = std::max(level, visit(index));
                 }
             }
             level = std::max(visit(indexAggregate.getExpression()), level);
             return std::max(level, visit(indexAggregate.getCondition()));
         }
         // unpack record
         int visitUnpackRecord(const RamUnpackRecord& unpack) override {
             return visit(unpack.getExpression());
         }
         // filter
         int visitFilter(const RamFilter& filter) override {
             return visit(filter.getCondition());
         }
         // break
         int visitBreak(const RamBreak& b) override {
             return visit(b.getCondition());
         }
         // project
         int visitProject(const RamProject& project) override {
             int level = -1;
             for (auto& exp : project.getValues()) {
                 if (exp != nullptr) {
                     level = std::max(level, visit(exp));
                 }
             }
             return level;
         }
         // return
         int visitReturnValue(const RamReturnValue& ret) override {
             int level = -1;
             for (auto& exp : ret.getValues()) {
                 if (exp != nullptr) {
                     level = std::max(level, visit(exp));
                 }
             }
             return level;
         }
         // auto increment
         int visitAutoIncrement(const RamAutoIncrement& increment) override {
             return -1;
         }
         // undef value
         int visitUndefValue(const RamUndefValue& undef) override {
             return -1;
         }
         // intrinsic functors
         int visitIntrinsicOperator(const RamIntrinsicOperator& op) override {
             int level = -1;
             for (const auto& arg : op.getArguments()) {
                 if (arg != nullptr) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
         // pack operator
         int visitPackRecord(const RamPackRecord& pack) override {
             int level = -1;
             for (const auto& arg : pack.getArguments()) {
                 if (arg != nullptr) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
         // argument
         int visitArgument(const RamArgument& arg) override {
             return -1;
         }
         // user defined operator
         int visitUserDefinedOperator(const RamUserDefinedOperator& op) override {
             int level = -1;
             for (const auto& arg : op.getArguments()) {
                 if (arg != nullptr) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
         // conjunction
         int visitConjunction(const RamConjunction& conj) override {
             return std::max(visit(conj.getLHS()), visit(conj.getRHS()));
         }
         // negation
         int visitNegation(const RamNegation& neg) override {
             return visit(neg.getOperand());
         }
         // constraint
         int visitConstraint(const RamConstraint& binRel) override {
             return std::max(visit(binRel.getLHS()), visit(binRel.getRHS()));
         }
         // existence check
         int visitExistenceCheck(const RamExistenceCheck& exists) override {
             int level = -1;
             for (const auto& cur : exists.getValues()) {
                 if (cur != nullptr) {
                     level = std::max(level, visit(cur));
                 }
             }
             return level;
         }
         // provenance existence check
         int visitProvenanceExistenceCheck(const RamProvenanceExistenceCheck& provExists) override {
             int level = -1;
             for (const auto& cur : provExists.getValues()) {
                 if (cur != nullptr) {
                     level = std::max(level, visit(cur));
                 }
             }
             return level;
         }
         // emptiness check
         int visitEmptinessCheck(const RamEmptinessCheck& emptiness) override {
             return -1;  // can be in the top level
         }
         // default rule
         int visitNode(const RamNode& node) override {
             assert(false && "RamNode not implemented!");
             return -1;
         }
     };
     assert((dynamic_cast<const RamExpression*>(node) != nullptr ||
                    dynamic_cast<const RamCondition*>(node) != nullptr ||
                    dynamic_cast<const RamOperation*>(node) != nullptr) &&
             "not an expression/condition/operation");
     return ValueLevelVisitor().visit(node);
 }
void souffle::RamLevelAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
run analysis for a RAM translation unit
Implements souffle::RamAnalysis.
Definition at line 45 of file RamLevelAnalysis.h.
References getLevel().
 {}
Field Documentation
constexpr const char* souffle::RamLevelAnalysis::name = "level-analysis" static
Definition at line 43 of file RamLevelAnalysis.h.
The documentation for this class was generated from the following files:
RamLevelAnalysis.h
RamLevelAnalysis.cpp