souffle: souffle::RamReturnValue Class Reference
souffle::RamReturnValue Class Reference
A statement for returning from a ram subroutine.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamReturnValue * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
std::vector< RamExpression * > getValues () const
void print (std::ostream &os, int tabpos) const override
pretty print with intentation
RamReturnValue (std::vector< std::unique_ptr< RamExpression >> vals)
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > expressions
Detailed Description
A statement for returning from a ram subroutine.
Definition at line 1001 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamReturnValue::RamReturnValue (std::vector< std::unique_ptr< RamExpression >> vals) inline
Definition at line 1003 of file RamOperation.h.
             : RamOperation(), expressions(std::move(vals)) {}
Member Function Documentation
void souffle::RamReturnValue::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 1050 of file RamOperation.h.
{
         for (auto& cur : expressions) {
             if (cur != nullptr) {
                 cur = map(std::move(cur));
             }
         }
     }
RamReturnValue* souffle::RamReturnValue::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 1038 of file RamOperation.h.
{
         std::vector<std::unique_ptr<RamExpression>> newValues;
         for (auto& cur : expressions) {
             if (cur != nullptr) {
                 newValues.emplace_back(cur->clone());
             } else {
                 newValues.push_back(nullptr);
             }
         }
         return new RamReturnValue(std::move(newValues));
     }
bool souffle::RamReturnValue::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 1061 of file RamOperation.h.
References souffle::equal_targets().
{
         assert(nullptr != dynamic_cast<const RamReturnValue*>(&node));
         const auto& other = static_cast<const RamReturnValue&>(node);
         return equal_targets(expressions, other.expressions);
     }
std::vector<const RamNode*> souffle::RamReturnValue::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamNode.
Definition at line 1028 of file RamOperation.h.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : expressions) {
             if (cur != nullptr) {
                 res.push_back(cur.get());
             }
         }
         return res;
     }
std::vector<RamExpression*> souffle::RamReturnValue::getValues () const inline
Definition at line 1023 of file RamOperation.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::RamLevelAnalysis::getLevel(), and souffle::LVMGenerator::visitReturnValue().
{
         return toPtrVector(expressions);
     }
void souffle::RamReturnValue::print (std::ostream & os, int tabpos) const inline override virtual
pretty print with intentation
Implements souffle::RamOperation.
Definition at line 1006 of file RamOperation.h.
References souffle::times().
{
         os << times(" ", tabpos);
         os << "RETURN (";
         for (auto val : getValues()) {
             if (val == nullptr) {
                 os << "_";
             } else {
                 val->print(os);
             }
             if (val != *(getValues().end() - 1)) {
                 os << ", ";
             }
         }
         os << ")" << std::endl;
     }
Field Documentation
std::vector<std::unique_ptr<RamExpression> > souffle::RamReturnValue::expressions protected
Definition at line 1059 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h